# Generated by Django 4.0 on 2024-02-12 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=254, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['description'],
            },
        ),
        migrations.AlterModelOptions(
            name='modeofpayment',
            options={'ordering': ['description'], 'verbose_name_plural': 'Modes of Payment'},
        ),
        migrations.AlterModelOptions(
            name='warranty',
            options={'ordering': ['description'], 'verbose_name_plural': 'Warranties'},
        ),
    ]
