# Generated by Django 4.0 on 2024-04-11 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0002_itemcondition_alter_modeofpayment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcondition',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='modeofpayment',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='repairwork',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='warranty',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10, verbose_name='Status'),
        ),
    ]
