# Generated by Django 4.0 on 2024-04-11 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0003_itemcondition_status_modeofpayment_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchCaliber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caliber', models.CharField(max_length=100, verbose_name='Caliber')),
                ('service_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Service Charge')),
            ],
        ),
    ]
