# Generated by Django 4.0 on 2024-04-11 18:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0004_watchcaliber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchcaliber',
            name='caliber',
        ),
        migrations.AddField(
            model_name='watchcaliber',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='watchcaliber',
            name='description',
            field=models.CharField(default='a', max_length=100, verbose_name='Description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='watchcaliber',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='watchcaliber',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
