# Generated by Django 4.0 on 2024-04-16 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joborder', '0011_remove_testlog_status'),
        ('customization', '0005_remove_watchcaliber_caliber_watchcaliber_created_at_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemCondition',
            new_name='ExternalCaseAndBracelet',
        ),
    ]
