# Generated by Django 4.0 on 2024-04-17 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0006_rename_itemcondition_externalcaseandbracelet'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=254, verbose_name='Description')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['description'],
            },
        ),
    ]
