# Generated by Django 4.0 on 2024-02-12 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='mob_num',
            field=models.CharField(default='', max_length=100, verbose_name='Mobile Number'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='tel_num',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Telephone Number'),
        ),
    ]
