# Generated by Django 4.0 on 2025-03-08 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_alter_client_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='Name')),
                ('address', models.TextField()),
                ('mob_num', models.CharField(max_length=100, verbose_name='Mobile Number')),
                ('tel_num', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telephone Number')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address')),
                ('issue', models.TextField(verbose_name='Initial watch repair issue')),
                ('is_watch_owner', models.BooleanField(default=False, verbose_name='Are you the watch owner?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
