# Generated by Django 4.0 on 2025-03-08 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_inquiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='issue',
            field=models.TextField(blank=True, null=True, verbose_name='Initial watch repair issue'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='mob_num',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Mobile Number'),
        ),
    ]
