# Generated by Django 4.0 on 2024-04-02 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access', '0001_initial'),
        ('client', '0002_alter_client_mob_num_alter_client_tel_num'),
        ('customization', '0002_itemcondition_alter_modeofpayment_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(max_length=100, verbose_name='Article')),
                ('serial_number', models.CharField(max_length=100, verbose_name='Serial Number')),
                ('case_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Case Number')),
                ('dial', models.CharField(blank=True, max_length=100, null=True, verbose_name='Dial')),
                ('bracelet', models.CharField(max_length=100, verbose_name='Bracelet')),
                ('components', models.CharField(max_length=100, verbose_name='Components')),
                ('watch_movement', models.CharField(blank=True, max_length=100, null=True, verbose_name='Watch Movement')),
                ('movement_caliber', models.CharField(blank=True, max_length=100, null=True, verbose_name='Movement Caliber')),
                ('movement_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Movement Number')),
                ('aesthetic_defects', models.CharField(blank=True, max_length=254, null=True, verbose_name='Aesthetic Defects')),
                ('for_him', models.BooleanField(default=True, verbose_name='For Him?')),
                ('for_her', models.BooleanField(default=True, verbose_name='For Her?')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_owner', to='client.client', verbose_name='Owner')),
            ],
        ),
        migrations.CreateModel(
            name='JobOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_technician_jo', to='access.employee', verbose_name='Assigned Technician')),
                ('item_condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_condition_jo', to='customization.itemcondition', verbose_name='Item Condition')),
                ('repair_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repair_work_jo', to='customization.repairwork', verbose_name='Repair Work')),
                ('watch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_jo', to='joborder.watch', verbose_name='Watch')),
            ],
        ),
    ]
