# Generated by Django 4.0 on 2024-04-05 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0001_initial'),
        ('customization', '0002_itemcondition_alter_modeofpayment_options_and_more'),
        ('joborder', '0002_joborder_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Particular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=254, verbose_name='Description')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Unit Price')),
            ],
        ),
        migrations.CreateModel(
            name='WatchCaliber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caliber', models.CharField(max_length=100, verbose_name='Caliber')),
                ('service_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Service Charge')),
            ],
        ),
        migrations.AddField(
            model_name='joborder',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Balance'),
        ),
        migrations.AddField(
            model_name='joborder',
            name='current_status',
            field=models.CharField(choices=[('SORTING', 'Sorting'), ('IN-QUEUE', 'In Queue'), ('ONGOING', 'Ongoing'), ('OBSERVATION', 'Observation'), ('SAFEKEEPING', 'Safekeeping'), ('PENDING', 'Pending'), ('FOR-ESTIMATE', 'For Estimate'), ('UNCLAIMED', 'Unclaimed'), ('CLAIMED', 'Claimed'), ('PULLED-OUT', 'Pulled Out'), ('NOT-REPAIRABLE', 'Not Repairable'), ('IN-HOUSE', 'In House'), ('FINISHED', 'Finished')], default='SORTING', max_length=25, verbose_name='Current Status'),
        ),
        migrations.AddField(
            model_name='joborder',
            name='total_charges',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Total Charges'),
        ),
        migrations.AddField(
            model_name='joborder',
            name='total_paid',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Total Paid'),
        ),
        migrations.AlterField(
            model_name='joborder',
            name='assigned_technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_technician_jo', to='access.employee', verbose_name='Assigned Technician'),
        ),
        migrations.AlterField(
            model_name='joborder',
            name='item_condition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_condition_jo', to='customization.itemcondition', verbose_name='Item Condition'),
        ),
        migrations.AlterField(
            model_name='joborder',
            name='repair_work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='repair_work_jo', to='customization.repairwork', verbose_name='Repair Work'),
        ),
        migrations.AlterField(
            model_name='joborder',
            name='watch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watch_jo', to='joborder.watch', verbose_name='Watch'),
        ),
        migrations.CreateModel(
            name='WorkToBeDone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notices', models.CharField(blank=True, max_length=254, null=True, verbose_name='Notices')),
                ('external_case_and_bracelet', models.CharField(blank=True, max_length=254, null=True, verbose_name='External Case and Bracelet')),
                ('condition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='condition', to='customization.itemcondition', verbose_name='Condition')),
                ('job_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_to_be_done_jo', to='joborder.joborder', verbose_name='Job Order')),
                ('warranty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warranty', to='customization.warranty', verbose_name='Warranty')),
            ],
        ),
        migrations.CreateModel(
            name='TestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('SORTING', 'Sorting'), ('IN-QUEUE', 'In Queue'), ('ONGOING', 'Ongoing'), ('OBSERVATION', 'Observation'), ('SAFEKEEPING', 'Safekeeping'), ('PENDING', 'Pending'), ('FOR-ESTIMATE', 'For Estimate'), ('UNCLAIMED', 'Unclaimed'), ('CLAIMED', 'Claimed'), ('PULLED-OUT', 'Pulled Out'), ('NOT-REPAIRABLE', 'Not Repairable'), ('IN-HOUSE', 'In House'), ('FINISHED', 'Finished')], default='SORTING', max_length=25, verbose_name='Status')),
                ('amplitude', models.PositiveIntegerField(blank=True, null=True, verbose_name='Amplitude')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Comments')),
                ('encoded_at', models.DateTimeField(auto_now_add=True)),
                ('job_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_log_jo', to='joborder.joborder', verbose_name='Job Order')),
                ('tested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tested_by', to='access.employee', verbose_name='Tested By')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Amount Paid')),
                ('or_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='OR Number')),
                ('date_paid', models.DateField(blank=True, null=True, verbose_name='Date Paid')),
                ('job_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_jo', to='joborder.joborder', verbose_name='Job Order')),
                ('mode_of_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mode_of_payment', to='customization.modeofpayment', verbose_name='Mode of Payment')),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_by', to='access.employee', verbose_name='Received By')),
            ],
        ),
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Service Fee')),
                ('parts', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Parts')),
                ('total_estimate', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total Estimate')),
                ('date_promised', models.DateField(blank=True, null=True, verbose_name='Date Promised')),
                ('job_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimate_jo', to='joborder.joborder', verbose_name='Job Order')),
            ],
        ),
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('particular', models.CharField(max_length=254, verbose_name='Particular')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Unit Price')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantity')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total Amount')),
                ('job_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charge_jo', to='joborder.joborder', verbose_name='Job Order')),
            ],
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment', models.TextField(verbose_name='Assessment')),
                ('encoded_at', models.DateTimeField(auto_now_add=True)),
                ('assessed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessed_by', to='access.employee', verbose_name='Assessed By')),
                ('job_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_jo', to='joborder.joborder', verbose_name='Job Order')),
            ],
        ),
        migrations.AlterField(
            model_name='watch',
            name='movement_caliber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movement_caliber', to='joborder.watchcaliber', verbose_name='Movement Caliber'),
        ),
    ]
