# Generated by Django 4.0 on 2024-04-11 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0004_watchcaliber'),
        ('joborder', '0003_particular_watchcaliber_joborder_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watch',
            name='movement_caliber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movement_caliber', to='customization.watchcaliber', verbose_name='Movement Caliber'),
        ),
        migrations.DeleteModel(
            name='WatchCaliber',
        ),
    ]
