# Generated by Django 4.0 on 2024-04-12 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('joborder', '0004_alter_watch_movement_caliber_delete_watchcaliber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joborder',
            name='watch',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watch_jo', to='joborder.watch', verbose_name='Watch'),
        ),
    ]
