# Generated by Django 4.0 on 2024-04-12 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('joborder', '0006_joborder_created_at_joborder_promise_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joborder',
            name='promise_date',
        ),
        migrations.AlterField(
            model_name='estimate',
            name='job_order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estimate_jo', to='joborder.joborder', verbose_name='Job Order'),
        ),
        migrations.AlterField(
            model_name='worktobedone',
            name='job_order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='work_to_be_done_jo', to='joborder.joborder', verbose_name='Job Order'),
        ),
    ]
