# Generated by Django 4.0 on 2024-04-12 08:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('joborder', '0007_remove_joborder_promise_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estimate',
            name='date_promised',
        ),
        migrations.AddField(
            model_name='joborder',
            name='promise_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Promise Date'),
        ),
    ]
