# Generated by Django 4.0 on 2024-04-15 08:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('joborder', '0008_remove_estimate_date_promised_joborder_promise_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='assessment_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Assessment Date'),
            preserve_default=False,
        ),
    ]
