# Generated by Django 4.0 on 2024-04-16 06:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('joborder', '0009_assessment_assessment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='testlog',
            name='tested_on',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Tested On'),
        ),
    ]
