# Generated by Django 4.0 on 2024-04-16 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joborder', '0010_testlog_tested_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testlog',
            name='status',
        ),
    ]
