# Generated by Django 4.0 on 2024-04-16 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0006_rename_itemcondition_externalcaseandbracelet'),
        ('joborder', '0011_remove_testlog_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joborder',
            name='item_condition',
        ),
        migrations.AddField(
            model_name='joborder',
            name='condition',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Condition'),
        ),
        migrations.AddField(
            model_name='joborder',
            name='external_case_and_bracelet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_bracelet_jo', to='customization.externalcaseandbracelet', verbose_name='External Case and Bracelet'),
        ),
        migrations.AddField(
            model_name='joborder',
            name='notices',
            field=models.TextField(blank=True, null=True, verbose_name='Notices'),
        ),
        migrations.AddField(
            model_name='joborder',
            name='warranty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warranty', to='customization.warranty', verbose_name='Warranty'),
        ),
        migrations.DeleteModel(
            name='WorkToBeDone',
        ),
    ]
