# Generated by Django 4.0 on 2024-04-16 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joborder', '0012_remove_joborder_item_condition_joborder_condition_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watch',
            name='aesthetic_defects',
        ),
        migrations.RemoveField(
            model_name='watch',
            name='components',
        ),
    ]
