# Generated by Django 4.0 on 2024-04-17 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joborder', '0014_watch_components'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='assessed_by',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='job_order',
        ),
        migrations.RemoveField(
            model_name='charge',
            name='job_order',
        ),
        migrations.RemoveField(
            model_name='estimate',
            name='job_order',
        ),
        migrations.RemoveField(
            model_name='joborder',
            name='assigned_technician',
        ),
        migrations.RemoveField(
            model_name='joborder',
            name='client',
        ),
        migrations.RemoveField(
            model_name='joborder',
            name='external_case_and_bracelet',
        ),
        migrations.RemoveField(
            model_name='joborder',
            name='repair_work',
        ),
        migrations.RemoveField(
            model_name='joborder',
            name='warranty',
        ),
        migrations.RemoveField(
            model_name='joborder',
            name='watch',
        ),
        migrations.DeleteModel(
            name='Particular',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='job_order',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='mode_of_payment',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='received_by',
        ),
        migrations.RemoveField(
            model_name='testlog',
            name='job_order',
        ),
        migrations.RemoveField(
            model_name='testlog',
            name='tested_by',
        ),
        migrations.RemoveField(
            model_name='watch',
            name='movement_caliber',
        ),
        migrations.RemoveField(
            model_name='watch',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Assessment',
        ),
        migrations.DeleteModel(
            name='Charge',
        ),
        migrations.DeleteModel(
            name='Estimate',
        ),
        migrations.DeleteModel(
            name='JobOrder',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='TestLog',
        ),
        migrations.DeleteModel(
            name='Watch',
        ),
    ]
