# Generated by Django 4.0 on 2024-04-17 02:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0002_alter_client_mob_num_alter_client_tel_num'),
        ('access', '0001_initial'),
        ('customization', '0006_rename_itemcondition_externalcaseandbracelet'),
        ('joborder', '0015_remove_assessment_assessed_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notices', models.TextField(blank=True, null=True, verbose_name='Notices')),
                ('condition', models.CharField(blank=True, max_length=254, null=True, verbose_name='Condition')),
                ('current_status', models.CharField(choices=[('SORTING', 'Sorting'), ('IN-QUEUE', 'In Queue'), ('ONGOING', 'Ongoing'), ('OBSERVATION', 'Observation'), ('SAFEKEEPING', 'Safekeeping'), ('PENDING', 'Pending'), ('FOR-ESTIMATE', 'For Estimate'), ('UNCLAIMED', 'Unclaimed'), ('CLAIMED', 'Claimed'), ('PULLED-OUT', 'Pulled Out'), ('NOT-REPAIRABLE', 'Not Repairable'), ('IN-HOUSE', 'In House'), ('FINISHED', 'Finished')], default='SORTING', max_length=25, verbose_name='Current Status')),
                ('total_charges', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Total Charges')),
                ('total_paid', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Total Paid')),
                ('balance', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Balance')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('promise_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Promise Date')),
                ('assigned_technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_technician_jo', to='access.employee', verbose_name='Assigned Technician')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_jo', to='client.client', verbose_name='Client')),
                ('external_case_and_bracelet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_bracelet_jo', to='customization.externalcaseandbracelet', verbose_name='External Case and Bracelet')),
                ('repair_work', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='repair_work_jo', to='customization.repairwork', verbose_name='Repair Work')),
                ('warranty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warranty', to='customization.warranty', verbose_name='Warranty')),
            ],
        ),
        migrations.CreateModel(
            name='Particular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=254, verbose_name='Description')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Unit Price')),
            ],
        ),
        migrations.CreateModel(
            name='Watch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(max_length=100, verbose_name='Article')),
                ('serial_number', models.CharField(max_length=100, verbose_name='Serial Number')),
                ('case_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Case Number')),
                ('dial', models.CharField(blank=True, max_length=100, null=True, verbose_name='Dial')),
                ('bracelet', models.CharField(max_length=100, verbose_name='Bracelet')),
                ('watch_movement', models.CharField(blank=True, max_length=100, null=True, verbose_name='Watch Movement')),
                ('movement_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Movement Number')),
                ('for_him', models.BooleanField(default=True, verbose_name='For Him?')),
                ('for_her', models.BooleanField(default=True, verbose_name='For Her?')),
                ('movement_caliber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movement_caliber', to='customization.watchcaliber', verbose_name='Movement Caliber')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_owner', to='client.client', verbose_name='Owner')),
            ],
        ),
        migrations.CreateModel(
            name='TestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amplitude', models.PositiveIntegerField(blank=True, null=True, verbose_name='Amplitude')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Comments')),
                ('tested_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Tested On')),
                ('encoded_at', models.DateTimeField(auto_now_add=True)),
                ('job_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_log_jo', to='joborder.joborder', verbose_name='Job Order')),
                ('tested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tested_by', to='access.employee', verbose_name='Tested By')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Amount Paid')),
                ('or_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='OR Number')),
                ('date_paid', models.DateField(blank=True, null=True, verbose_name='Date Paid')),
                ('job_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_jo', to='joborder.joborder', verbose_name='Job Order')),
                ('mode_of_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mode_of_payment', to='customization.modeofpayment', verbose_name='Mode of Payment')),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_by', to='access.employee', verbose_name='Received By')),
            ],
        ),
        migrations.AddField(
            model_name='joborder',
            name='watch',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watch_jo', to='joborder.watch', verbose_name='Watch'),
        ),
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Service Fee')),
                ('parts', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Parts')),
                ('total_estimate', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total Estimate')),
                ('job_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estimate_jo', to='joborder.joborder', verbose_name='Job Order')),
            ],
        ),
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('particular', models.CharField(max_length=254, verbose_name='Particular')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Unit Price')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantity')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total Amount')),
                ('job_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charge_jo', to='joborder.joborder', verbose_name='Job Order')),
            ],
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment', models.TextField(verbose_name='Assessment')),
                ('assessment_date', models.DateField(verbose_name='Assessment Date')),
                ('encoded_at', models.DateTimeField(auto_now_add=True)),
                ('assessed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessed_by', to='access.employee', verbose_name='Assessed By')),
                ('job_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_jo', to='joborder.joborder', verbose_name='Job Order')),
            ],
        ),
    ]
