# Generated by Django 4.0 on 2024-04-17 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joborder', '0016_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='watch',
            name='aesthetic_defect',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Aesthetic Defects'),
        ),
        migrations.AddField(
            model_name='watch',
            name='component',
            field=models.CharField(default='', max_length=100, verbose_name='Components'),
            preserve_default=False,
        ),
    ]
