# Generated by Django 4.0 on 2024-04-17 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joborder', '0017_watch_aesthetic_defect_watch_component'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watch',
            name='bracelet',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bracelet'),
        ),
        migrations.AlterField(
            model_name='watch',
            name='component',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Components'),
        ),
        migrations.AlterField(
            model_name='watch',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Serial Number'),
        ),
    ]
