# Generated by Django 4.0 on 2024-04-17 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0007_watchmovement'),
        ('joborder', '0018_alter_watch_bracelet_alter_watch_component_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watch',
            name='movement_caliber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='caliber_watches', to='customization.watchcaliber', verbose_name='Movement Caliber'),
        ),
        migrations.AlterField(
            model_name='watch',
            name='watch_movement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movement_watches', to='customization.watchmovement', verbose_name='Watch Movement'),
        ),
    ]
