# Generated by Django 4.0 on 2024-04-17 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joborder', '0019_alter_watch_movement_caliber_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charge',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='joborder',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='joborder',
            name='total_charges',
        ),
        migrations.RemoveField(
            model_name='joborder',
            name='total_paid',
        ),
    ]
