# Generated by Django 4.0 on 2024-04-25 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('joborder', '0020_remove_charge_total_amount_remove_joborder_balance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleasePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(upload_to='photos/release')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('job_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releasephoto_jo', to='joborder.joborder', verbose_name='Job Order')),
            ],
        ),
        migrations.CreateModel(
            name='ArrivalPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(upload_to='photos/arrival/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('job_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrivalphoto_jo', to='joborder.joborder', verbose_name='Job Order')),
            ],
        ),
    ]
