# Generated by Django 4.0 on 2024-04-25 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joborder', '0021_releasephoto_arrivalphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrivalphoto',
            name='photo',
            field=models.ImageField(upload_to='photos/arrival/'),
        ),
        migrations.AlterField(
            model_name='releasephoto',
            name='photo',
            field=models.ImageField(upload_to='photos/release'),
        ),
    ]
