# Generated by Django 4.0 on 2024-04-29 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joborder', '0022_alter_arrivalphoto_photo_alter_releasephoto_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='joborder',
            name='closed_at',
            field=models.DateField(blank=True, null=True, verbose_name='Closed At'),
        ),
    ]
