# Generated by Django 4.0 on 2024-04-29 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joborder', '0023_joborder_closed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='watch',
            name='with_card',
            field=models.BooleanField(default=True, verbose_name='with Guarantee/Warranty Card?'),
        ),
        migrations.AlterField(
            model_name='joborder',
            name='current_status',
            field=models.CharField(choices=[('SORTING', 'Sorting'), ('IN-QUEUE', 'In Queue'), ('ONGOING', 'Ongoing'), ('OBSERVATION', 'Observation'), ('SAFEKEEPING', 'Safekeeping'), ('PARTS WAITING', 'Parts Waiting'), ('PENDING', 'Pending'), ('FOR-ESTIMATE', 'For Estimate'), ('UNCLAIMED', 'Unclaimed'), ('CLAIMED', 'Claimed'), ('PULLED-OUT', 'Pulled Out'), ('NOT-REPAIRABLE', 'Not Repairable'), ('IN-HOUSE', 'In House'), ('FINISHED', 'Finished')], default='SORTING', max_length=25, verbose_name='Current Status'),
        ),
    ]
