# Generated by Django 4.0 on 2024-06-03 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joborder', '0024_watch_with_card_alter_joborder_current_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='joborder',
            name='warranty_file_1',
            field=models.FileField(blank=True, null=True, upload_to='warranty', verbose_name='Warranty File 1'),
        ),
        migrations.AddField(
            model_name='joborder',
            name='warranty_file_2',
            field=models.FileField(blank=True, null=True, upload_to='warranty', verbose_name='Warranty File 2'),
        ),
        migrations.AddField(
            model_name='joborder',
            name='warranty_file_3',
            field=models.FileField(blank=True, null=True, upload_to='warranty', verbose_name='Warranty File 3'),
        ),
    ]
