# Generated by Django 4.0 on 2024-10-15 01:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('joborder', '0025_joborder_warranty_file_1_joborder_warranty_file_2_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='joborder',
            options={'ordering': ['-pk']},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-pk']},
        ),
        migrations.AddField(
            model_name='payment',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='joborder',
            name='current_status',
            field=models.CharField(choices=[('SORTING', 'Sorting'), ('IN-QUEUE', 'In Queue'), ('ONGOING', 'Ongoing'), ('OBSERVATION', 'Observation'), ('SAFEKEEPING', 'Safekeeping'), ('PARTS WAITING', 'Parts Waiting'), ('PENDING', 'Pending'), ('FOR-ESTIMATE', 'For Estimate'), ('UNCLAIMED', 'Unclaimed'), ('CLAIMED', 'Claimed'), ('PULLED-OUT', 'Pulled Out'), ('NOT-REPAIRABLE', 'Not Repairable'), ('IN-HOUSE', 'In House'), ('FINISHED', 'Finished'), ('CANCELLED', 'Cancelled')], default='SORTING', max_length=25, verbose_name='Current Status'),
        ),
    ]
