# Generated by Django 4.0 on 2025-02-24 13:55

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joborder', '0026_alter_joborder_options_alter_payment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrivalphoto',
            name='photo',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='or_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Service Invoice'),
        ),
        migrations.AlterField(
            model_name='releasephoto',
            name='photo',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
