# Generated by Django 4.0 on 2025-02-25 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_alter_client_options'),
        ('joborder', '0027_alter_arrivalphoto_photo_alter_payment_or_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joborder',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_jo', to='client.client', verbose_name='Client'),
        ),
    ]
