# Generated by Django 4.0 on 2025-02-28 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_alter_client_options'),
        ('joborder', '0028_alter_joborder_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watch',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watch_owner', to='client.client', verbose_name='Owner'),
        ),
    ]
