# Generated by Django 4.0 on 2025-03-01 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('joborder', '0029_alter_watch_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOrderStatusUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('SORTING', 'Sorting'), ('IN-QUEUE', 'In Queue'), ('ONGOING', 'Ongoing'), ('OBSERVATION', 'Observation'), ('SAFEKEEPING', 'Safekeeping'), ('PARTS WAITING', 'Parts Waiting'), ('PENDING', 'Pending'), ('FOR-ESTIMATE', 'For Estimate'), ('UNCLAIMED', 'Unclaimed'), ('CLAIMED', 'Claimed'), ('PULLED-OUT', 'Pulled Out'), ('NOT-REPAIRABLE', 'Not Repairable'), ('IN-HOUSE', 'In House'), ('FINISHED', 'Finished'), ('CANCELLED', 'Cancelled')], max_length=25, verbose_name='Status')),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('job_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statusupdate_jo', to='joborder.joborder', verbose_name='Job Order')),
            ],
        ),
    ]
