# Generated by Django 4.0 on 2026-02-22 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0007_alter_employee_user_type'),
        ('joborder', '0030_joborderstatusupdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSRLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interacted_on', models.DateTimeField(auto_now_add=True)),
                ('channel', models.CharField(max_length=50)),
                ('summary', models.TextField()),
                ('quoted_eta', models.DateTimeField(blank=True, null=True)),
                ('quoted_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('comment_notes', models.TextField(blank=True, null=True)),
                ('next_action_owner', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('closed', 'Closed')], default='open', max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('job_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='csrlogs_jo', to='joborder.joborder', verbose_name='Job Order')),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='csrlogs_csr', to='access.employee', verbose_name='CSR')),
            ],
        ),
    ]
