# Generated by Django 4.0 on 2025-02-24 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0003_alter_employee_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='user_type',
            field=models.IntegerField(choices=[(1, 'Technician'), (2, 'Encoders / Customer Service / Aftersales & Telemarketing'), (3, 'Parts Department'), (4, 'Inventory & Purchasing Department'), (5, 'Watch Security & Repair Coordinator'), (6, 'HR Department'), (7, 'Finance/Accounting'), (8, 'Operations Manager'), (9, 'Administrator')]),
        ),
    ]
