# Generated by Django 4.0 on 2026-02-18 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('access', '0005_userassignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userassignment',
            name='employee',
        ),
        migrations.AddField(
            model_name='userassignment',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
