# Generated by Django 4.0 on 2026-02-22 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0006_remove_userassignment_employee_userassignment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='user_type',
            field=models.IntegerField(choices=[(101, 'Technician'), (201, 'Encoders'), (202, 'Customer Service / Aftersales & Telemarketing'), (301, 'Parts Department'), (401, 'Inventory & Purchasing Department'), (501, 'Watch Security & Repair Coordinator'), (601, 'HR Department'), (701, 'Finance/Accounting'), (801, 'Operations Manager'), (999, 'Administrator')]),
        ),
    ]
